export { MovieAbout } from './MovieAbout'
export { Home } from './Home'
export { Discover } from './Discover'
export { Auth } from './Auth'
export { Feed } from './Feed'
export { Error } from './Error'
export { User } from './User'
