export const mock = {
  items: [
    {
      adult: false,
      backdrop_path: '/srYya1ZlI97Au4jUYAktDe3avyA.jpg',
      genre_ids: [14, 28, 12],
      id: 464052,
      original_language: 'en',
      original_title: 'Wonder Woman 1984',
      overview:
        'Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.',
      popularity: 1927.057,
      poster_path: '/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
      release_date: '2020-12-16',
      title: 'Wonder Woman 1984',
      video: false,
      vote_average: 6.9,
      vote_count: 3689,
    },
    {
      adult: false,
      backdrop_path: '/vfuzELmhBjBTswXj2Vqxnu5ge4g.jpg',
      genre_ids: [53, 80],
      id: 602269,
      original_language: 'en',
      original_title: 'The Little Things',
      overview:
        'Deputy Sheriff Joe "Deke" Deacon joins forces with Sgt. Jim Baxter to search for a serial killer who\'s terrorizing Los Angeles. As they track the culprit, Baxter is unaware that the investigation is dredging up echoes of Deke\'s past, uncovering disturbing secrets that could threaten more than his case.',
      popularity: 1231.823,
      poster_path: '/c7VlGCCgM9GZivKSzBgzuOVxQn7.jpg',
      release_date: '2021-01-28',
      title: 'The Little Things',
      video: false,
      vote_average: 6.4,
      vote_count: 324,
    },
    {
      adult: false,
      backdrop_path: '/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg',
      genre_ids: [10751, 16, 35, 18, 10402, 14],
      id: 508442,
      original_language: 'en',
      original_title: 'Soul',
      overview:
        'Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.',
      popularity: 883.461,
      poster_path: '/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
      release_date: '2020-12-25',
      title: 'Soul',
      video: false,
      vote_average: 8.3,
      vote_count: 4832,
    },
    {
      adult: false,
      backdrop_path: '/fX8e94MEWSuTJExndVYxKsmA4Hw.jpg',
      genre_ids: [28, 12, 80],
      id: 604822,
      original_language: 'zh',
      original_title: '急先锋',
      overview:
        "Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.",
      popularity: 866.595,
      poster_path: '/vYvppZMvXYheYTWVd8Rnn9nsmNp.jpg',
      release_date: '2020-09-30',
      title: 'Vanguard',
      video: false,
      vote_average: 6.5,
      vote_count: 195,
    },
    {
      adult: false,
      backdrop_path: '/wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
      genre_ids: [28, 53, 878],
      id: 577922,
      original_language: 'en',
      original_title: 'Tenet',
      overview:
        'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
      popularity: 636.959,
      poster_path: '/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
      release_date: '2020-08-22',
      title: 'Tenet',
      video: false,
      vote_average: 7.3,
      vote_count: 4416,
    },
    {
      adult: false,
      backdrop_path: '/8tNX8s3j1O0eqilOQkuroRLyOZA.jpg',
      genre_ids: [14, 28, 12],
      id: 458576,
      original_language: 'en',
      original_title: 'Monster Hunter',
      overview:
        'A portal transports Lt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.',
      popularity: 620.869,
      poster_path: '/uwjaCH7PiWrkz7oWJ4fcL3xGrb0.jpg',
      release_date: '2020-12-03',
      title: 'Monster Hunter',
      video: false,
      vote_average: 6.6,
      vote_count: 293,
    },
    {
      adult: false,
      backdrop_path: '/cjaOSjsjV6cl3uXdJqimktT880L.jpg',
      genre_ids: [10751, 12, 14, 16],
      id: 529203,
      original_language: 'en',
      original_title: 'The Croods: A New Age',
      overview:
        "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
      popularity: 574.131,
      poster_path: '/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg',
      release_date: '2020-11-25',
      title: 'The Croods: A New Age',
      video: false,
      vote_average: 7.6,
      vote_count: 1507,
    },
    {
      adult: false,
      backdrop_path: '/2M2JxEv3HSpjnZWjY9NOdGgfUd.jpg',
      genre_ids: [53, 28, 80, 18],
      id: 553604,
      original_language: 'en',
      original_title: 'Honest Thief',
      overview:
        "A bank robber tries to turn himself in because he's falling in love and wants to live an honest life...but when he realizes the Feds are more corrupt than him, he must fight back to clear his name.",
      popularity: 521.957,
      poster_path: '/zeD4PabP6099gpE0STWJrJrCBCs.jpg',
      release_date: '2020-09-03',
      title: 'Honest Thief',
      video: false,
      vote_average: 6.6,
      vote_count: 605,
    },
    {
      adult: false,
      backdrop_path: '/mBbA77FyzhU0Tz9tmbKG8heGmh3.jpg',
      genre_ids: [878, 18, 27],
      id: 594718,
      original_language: 'ru',
      original_title: 'Спутник',
      overview:
        'At the height of the Cold War, a Soviet spacecraft crash lands after a mission gone awry, leaving the commander as its only survivor. After a renowned Russian psychologist is brought in to evaluate the commander’s mental state, it becomes clear that something dangerous may have come back to Earth with him…',
      popularity: 498.215,
      poster_path: '/eAUzmhP54bE1vPXaY7FbuZREJlR.jpg',
      release_date: '2020-09-08',
      title: 'Sputnik',
      video: false,
      vote_average: 6.4,
      vote_count: 187,
    },
  ],

  single: {
    adult: false,
    backdrop_path: '/cjaOSjsjV6cl3uXdJqimktT880L.jpg',
    belongs_to_collection: {
      id: 464577,
      name: 'The Croods Collection',
      poster_path: '/ngKY2KzudNpC7j8a0OWjJRY0tHv.jpg',
      backdrop_path: '/8MjzBahFKCuQbwytpPPds7qboQa.jpg',
    },
    budget: 65000000,
    genres: [
      { id: 10751, name: 'Family' },
      { id: 12, name: 'Adventure' },
      { id: 14, name: 'Fantasy' },
      { id: 16, name: 'Animation' },
    ],
    homepage: 'https://www.dreamworks.com/movies/the-croods-2',
    id: 529203,
    imdb_id: 'tt2850386',
    original_language: 'en',
    original_title: 'The Croods: A New Age',
    overview:
      "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
    popularity: 574.131,
    poster_path: '/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg',
    production_companies: [
      {
        id: 33,
        logo_path: '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
        name: 'Universal Pictures',
        origin_country: 'US',
      },
      {
        id: 521,
        logo_path: '/kP7t6RwGz2AvvTkvnI1uteEwHet.png',
        name: 'DreamWorks Animation',
        origin_country: 'US',
      },
    ],
    production_countries: [
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    release_date: '2020-11-25',
    revenue: 135076090,
    runtime: 95,
    spoken_languages: [
      { english_name: 'English', iso_639_1: 'en', name: 'English' },
    ],
    status: 'Released',
    tagline: "The future ain't what it used to be.",
    title: 'The Croods: A New Age',
    video: false,
    vote_average: 7.6,
    vote_count: 1507,
  },
}
