export const mock = {
  items: [
    {
      adult: false,
      backdrop_path: '/drulhSX7P5TQlEMQZ3JoXKSDEfz.jpg',
      genre_ids: [18, 14, 878],
      id: 581389,
      original_language: 'ko',
      original_title: '승리호',
      overview:
        "When the crew of a space junk collector ship called The Victory discovers a humanoid robot named Dorothy that's known to be a weapon of mass destruction, they get involved in a risky business deal which puts their lives at stake.",
      popularity: 3287.863,
      poster_path: '/bmemsraCG1kIthY74NjDnnLRT2Q.jpg',
      release_date: '2021-02-05',
      title: 'Space Sweepers',
      video: false,
      vote_average: 7.2,
      vote_count: 249,
    },
    {
      adult: false,
      backdrop_path: '/srYya1ZlI97Au4jUYAktDe3avyA.jpg',
      genre_ids: [14, 28, 12],
      id: 464052,
      original_language: 'en',
      original_title: 'Wonder Woman 1984',
      overview:
        'Wonder Woman comes into conflict with the Soviet Union during the Cold War in the 1980s and finds a formidable foe by the name of the Cheetah.',
      popularity: 2421.374,
      poster_path: '/8UlWHLMpgZm9bx6QYh0NFoq67TZ.jpg',
      release_date: '2020-12-16',
      title: 'Wonder Woman 1984',
      video: false,
      vote_average: 6.9,
      vote_count: 3799,
    },
    {
      adult: false,
      backdrop_path: '/6TPZSJ06OEXeelx1U1VIAt0j9Ry.jpg',
      genre_ids: [28, 80, 53],
      id: 587996,
      original_language: 'es',
      original_title: 'Bajocero',
      overview:
        'When a prisoner transfer van is attacked, the cop in charge must fight those inside and outside while dealing with a silent foe: the icy temperatures.',
      popularity: 1848.689,
      poster_path: '/dWSnsAGTfc8U27bWsy2RfwZs0Bs.jpg',
      release_date: '2021-01-29',
      title: 'Below Zero',
      video: false,
      vote_average: 6.4,
      vote_count: 344,
    },
    {
      adult: false,
      backdrop_path: '/vfuzELmhBjBTswXj2Vqxnu5ge4g.jpg',
      genre_ids: [53, 80],
      id: 602269,
      original_language: 'en',
      original_title: 'The Little Things',
      overview:
        'Deputy Sheriff Joe "Deke" Deacon joins forces with Sgt. Jim Baxter to search for a serial killer who\'s terrorizing Los Angeles. As they track the culprit, Baxter is unaware that the investigation is dredging up echoes of Deke\'s past, uncovering disturbing secrets that could threaten more than his case.',
      popularity: 1792.244,
      poster_path: '/c7VlGCCgM9GZivKSzBgzuOVxQn7.jpg',
      release_date: '2021-01-28',
      title: 'The Little Things',
      video: false,
      vote_average: 6.4,
      vote_count: 360,
    },
    {
      adult: false,
      backdrop_path: '/lOSdUkGQmbAl5JQ3QoHqBZUbZhC.jpg',
      genre_ids: [53, 28, 878],
      id: 775996,
      original_language: 'en',
      original_title: 'Outside the Wire',
      overview:
        'In the near future, a drone pilot is sent into a deadly militarized zone and must work with an android officer to locate a doomsday device.',
      popularity: 1647.039,
      poster_path: '/6XYLiMxHAaCsoyrVo38LBWMw2p8.jpg',
      release_date: '2021-01-15',
      title: 'Outside the Wire',
      video: false,
      vote_average: 6.5,
      vote_count: 724,
    },
    {
      adult: false,
      backdrop_path: '/z8TvnEVRenMSTemxYZwLGqFofgF.jpg',
      genre_ids: [14, 28, 12],
      id: 458576,
      original_language: 'en',
      original_title: 'Monster Hunter',
      overview:
        'A portal transports Lt. Artemis and an elite unit of soldiers to a strange world where powerful monsters rule with deadly ferocity. Faced with relentless danger, the team encounters a mysterious hunter who may be their only hope to find a way home.',
      popularity: 1703.666,
      poster_path: '/1UCOF11QCw8kcqvce8LKOO6pimh.jpg',
      release_date: '2020-12-03',
      title: 'Monster Hunter',
      video: false,
      vote_average: 7.1,
      vote_count: 564,
    },
    {
      adult: false,
      backdrop_path: '/nz8xWrTKZzA5A7FgxaM4kfAoO1W.jpg',
      genre_ids: [878, 28],
      id: 651571,
      original_language: 'en',
      original_title: 'Breach',
      overview:
        'A hardened mechanic must stay awake and maintain an interstellar ark fleeing the dying planet Earth with a few thousand lucky souls on board... the last of humanity. Unfortunately, humans are not the only passengers. A shapeshifting alien creature has taken residence, its only goal is to kill as many people as possible. The crew must think quickly to stop this menace before it destroys mankind.',
      popularity: 1425.323,
      poster_path: '/13B6onhL6FzSN2KaNeQeMML05pS.jpg',
      release_date: '2020-12-17',
      title: 'Breach',
      video: false,
      vote_average: 4.6,
      vote_count: 272,
    },
    {
      adult: false,
      backdrop_path: '/fRrpOILyXuWaWLmqF7kXeMVwITQ.jpg',
      genre_ids: [27, 53, 12],
      id: 522444,
      original_language: 'en',
      original_title: 'Black Water: Abyss',
      overview:
        'An adventure-loving couple convince their friends to explore a remote, uncharted cave system in the forests of Northern Australia. With a tropical storm approaching, they abseil into the mouth of the cave, but when the caves start to flood, tensions rise as oxygen levels fall and the friends find themselves trapped. Unknown to them, the storm has also brought in a pack of dangerous and hungry crocodiles.',
      popularity: 1435.372,
      poster_path: '/95S6PinQIvVe4uJAd82a2iGZ0rA.jpg',
      release_date: '2020-07-09',
      title: 'Black Water: Abyss',
      video: false,
      vote_average: 5.1,
      vote_count: 137,
    },
    {
      adult: false,
      backdrop_path: '/fX8e94MEWSuTJExndVYxKsmA4Hw.jpg',
      genre_ids: [28, 12, 80],
      id: 604822,
      original_language: 'zh',
      original_title: '急先锋',
      overview:
        "Covert security company Vanguard is the last hope of survival for an accountant after he is targeted by the world's deadliest mercenary organization.",
      popularity: 1182.817,
      poster_path: '/vYvppZMvXYheYTWVd8Rnn9nsmNp.jpg',
      release_date: '2020-09-30',
      title: 'Vanguard',
      video: false,
      vote_average: 6.5,
      vote_count: 200,
    },
    {
      adult: false,
      backdrop_path: '/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg',
      genre_ids: [28, 12, 53],
      id: 581387,
      original_language: 'ko',
      original_title: '백두산',
      overview:
        "Stagnant since 1903, at an elevation of 9000', a volcano erupts on the mythical and majestic Baekdu Mountain.",
      popularity: 1190.94,
      poster_path: '/zoeKREZ2IdAUnXISYCS0E6H5BVh.jpg',
      release_date: '2019-12-19',
      title: 'Ashfall',
      video: false,
      vote_average: 6.6,
      vote_count: 195,
    },
    {
      adult: false,
      backdrop_path: '/kf456ZqeC45XTvo6W9pW5clYKfQ.jpg',
      genre_ids: [10751, 16, 35, 18, 10402, 14],
      id: 508442,
      original_language: 'en',
      original_title: 'Soul',
      overview:
        'Joe Gardner is a middle school teacher with a love for jazz music. After a successful gig at the Half Note Club, he suddenly gets into an accident that separates his soul from his body and is transported to the You Seminar, a center in which souls develop and gain passions before being transported to a newborn child. Joe must enlist help from the other souls-in-training, like 22, a soul who has spent eons in the You Seminar, in order to get back to Earth.',
      popularity: 1092.634,
      poster_path: '/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg',
      release_date: '2020-12-25',
      title: 'Soul',
      video: false,
      vote_average: 8.3,
      vote_count: 4894,
    },
    {
      adult: false,
      backdrop_path: '/9xeEGUZjgiKlI69jwIOi0hjKUIk.jpg',
      genre_ids: [14, 28, 12, 16],
      id: 664767,
      original_language: 'en',
      original_title: "Mortal Kombat Legends: Scorpion's Revenge",
      overview:
        'After the vicious slaughter of his family by stone-cold mercenary Sub-Zero, Hanzo Hasashi is exiled to the torturous Netherrealm. There, in exchange for his servitude to the sinister Quan Chi, he’s given a chance to avenge his family – and is resurrected as Scorpion, a lost soul bent on revenge. Back on Earthrealm, Lord Raiden gathers a team of elite warriors – Shaolin monk Liu Kang, Special Forces officer Sonya Blade and action star Johnny Cage – an unlikely band of heroes with one chance to save humanity. To do this, they must defeat Shang Tsung’s horde of Outworld gladiators and reign over the Mortal Kombat tournament.',
      popularity: 1210.723,
      poster_path: '/4VlXER3FImHeFuUjBShFamhIp9M.jpg',
      release_date: '2020-04-12',
      title: "Mortal Kombat Legends: Scorpion's Revenge",
      video: false,
      vote_average: 8.4,
      vote_count: 754,
    },
    {
      adult: false,
      backdrop_path: '/3ombg55JQiIpoPnXYb2oYdr6DtP.jpg',
      genre_ids: [878, 28],
      id: 560144,
      original_language: 'en',
      original_title: 'Skylines',
      overview:
        "When a virus threatens to turn the now earth-dwelling friendly alien hybrids against humans, Captain Rose Corley must lead a team of elite mercenaries on a mission to the alien world in order to save what's left of humanity.",
      popularity: 1079.58,
      poster_path: '/2W4ZvACURDyhiNnSIaFPHfNbny3.jpg',
      release_date: '2020-10-25',
      title: 'Skylines',
      video: false,
      vote_average: 5.7,
      vote_count: 176,
    },
    {
      adult: false,
      backdrop_path: '/fAJuZDEkrqmYQUUDrro8wRqb2Tn.jpg',
      genre_ids: [35, 18, 10749],
      id: 614409,
      original_language: 'en',
      original_title: 'To All the Boys: Always and Forever',
      overview:
        'Senior year of high school takes center stage as Lara Jean returns from a family trip to Korea and considers her college plans — with and without Peter.',
      popularity: 927.595,
      poster_path: '/zdkJs9j6yKo9di0kjtctM01fSMv.jpg',
      release_date: '2021-02-12',
      title: 'To All the Boys: Always and Forever',
      video: false,
      vote_average: 8,
      vote_count: 839,
    },
    {
      adult: false,
      backdrop_path: '/yImmxRokQ48PD49ughXdpKTAsAU.jpg',
      genre_ids: [28, 12, 35, 10751],
      id: 644092,
      original_language: 'en',
      original_title: "Finding 'Ohana",
      overview:
        "Two Brooklyn siblings' summer in a rural Oahu town takes an exciting turn when a journal pointing to long-lost treasure sets them on an adventure, leading them to reconnect with their Hawaiian heritage.",
      popularity: 832.194,
      poster_path: '/tTWl37oAYRXS3D5mEHmjveXXyrN.jpg',
      release_date: '2021-01-29',
      title: "Finding 'Ohana",
      video: false,
      vote_average: 6.7,
      vote_count: 143,
    },
    {
      adult: false,
      backdrop_path: '/7KL4yJ4JsbtS1BNRilUApLvMnc5.jpg',
      genre_ids: [18, 53],
      id: 649087,
      original_language: 'sv',
      original_title: 'Red Dot',
      overview:
        'On a hiking trip to rekindle their marriage, a couple find themselves fleeing for their lives in the unforgiving wilderness from an unknown shooter.',
      popularity: 1142.623,
      poster_path: '/xZ2KER2gOHbuHP2GJoODuXDSZCb.jpg',
      release_date: '2021-02-11',
      title: 'Red Dot',
      video: false,
      vote_average: 6.2,
      vote_count: 182,
    },
    {
      adult: false,
      backdrop_path: '/wzJRB4MKi3yK138bJyuL9nx47y6.jpg',
      genre_ids: [28, 53, 878],
      id: 577922,
      original_language: 'en',
      original_title: 'Tenet',
      overview:
        'Armed with only one word - Tenet - and fighting for the survival of the entire world, the Protagonist journeys through a twilight world of international espionage on a mission that will unfold in something beyond real time.',
      popularity: 887.293,
      poster_path: '/k68nPLbIST6NP96JmTxmZijEvCA.jpg',
      release_date: '2020-08-22',
      title: 'Tenet',
      video: false,
      vote_average: 7.3,
      vote_count: 4458,
    },
    {
      adult: false,
      backdrop_path: '/54yOImQgj8i85u9hxxnaIQBRUuo.jpg',
      genre_ids: [28, 80, 18, 53],
      id: 539885,
      original_language: 'en',
      original_title: 'Ava',
      overview:
        'A black ops assassin is forced to fight for her own survival after a job goes dangerously wrong.',
      popularity: 837.911,
      poster_path: '/qzA87Wf4jo1h8JMk9GilyIYvwsA.jpg',
      release_date: '2020-07-02',
      title: 'Ava',
      video: false,
      vote_average: 5.6,
      vote_count: 1291,
    },
    {
      adult: false,
      backdrop_path: '/7TxeZVg2evMG42p0uSbMJpWNQ8A.jpg',
      genre_ids: [10751, 16, 14],
      id: 520946,
      original_language: 'en',
      original_title: '100% Wolf',
      overview:
        "Freddy Lupin, heir to a proud family line of werewolves, is in for a shock when on his 14th birthday his first 'warfing' goes awry, turning him into a ferocious poodle. The pack elders give Freddy until the next moonrise to prove he has the heart of a wolf, or risk being cast out forever. With the help of an unlikely ally in a streetwise stray named Batty, Freddy must prove he's 100% Wolf.",
      popularity: 723.149,
      poster_path: '/2VrvxK4yxNCU6KVgo5TADJeBEQu.jpg',
      release_date: '2020-06-26',
      title: '100% Wolf',
      video: false,
      vote_average: 5.9,
      vote_count: 82,
    },
    {
      adult: false,
      backdrop_path: '/cjaOSjsjV6cl3uXdJqimktT880L.jpg',
      genre_ids: [10751, 12, 14, 16],
      id: 529203,
      original_language: 'en',
      original_title: 'The Croods: A New Age',
      overview:
        "Searching for a safer habitat, the prehistoric Crood family discovers an idyllic, walled-in paradise that meets all of its needs. Unfortunately, they must also learn to live with the Bettermans -- a family that's a couple of steps above the Croods on the evolutionary ladder. As tensions between the new neighbors start to rise, a new threat soon propels both clans on an epic adventure that forces them to embrace their differences, draw strength from one another, and survive together.",
      popularity: 799.234,
      poster_path: '/tK1zy5BsCt1J4OzoDicXmr0UTFH.jpg',
      release_date: '2020-11-25',
      title: 'The Croods: A New Age',
      video: false,
      vote_average: 7.6,
      vote_count: 1528,
    },
  ],

  single: {
    adult: false,
    backdrop_path: '/8moTOzunF7p40oR5XhlDvJckOSW.jpg',
    belongs_to_collection: {
      id: 477962,
      name: 'It Collection',
      poster_path: '/tZ55C7gPExwzvBLCsZMqFZMbB2I.jpg',
      backdrop_path: '/ayvH5IW5eDOa28WfSjnkYMii73d.jpg',
    },
    budget: 79000000,
    genres: [
      { id: 27, name: 'Horror' },
      { id: 14, name: 'Fantasy' },
    ],
    homepage: 'http://www.it-movie.net/',
    id: 474350,
    imdb_id: 'tt7349950',
    original_language: 'en',
    original_title: 'It Chapter Two',
    overview:
      "27 years after overcoming the malevolent supernatural entity Pennywise, the former members of the Losers' Club, who have grown up and moved away from Derry, are brought back together by a devastating phone call.",
    popularity: 149.588,
    poster_path: '/zfE0R94v1E8cuKAerbskfD3VfUt.jpg',
    production_companies: [
      { id: 2723, logo_path: null, name: 'Lin Pictures', origin_country: 'US' },
      {
        id: 12,
        logo_path: '/iaYpEp3LQmb8AfAtmTvpqd4149c.png',
        name: 'New Line Cinema',
        origin_country: 'US',
      },
      {
        id: 829,
        logo_path: '/mzpAmEQ5P1gFvdRoNyCk9q8ngiv.png',
        name: 'Vertigo Entertainment',
        origin_country: 'US',
      },
      {
        id: 87671,
        logo_path: '/kEEGB5Z2XLYeR3AMt3Qds7vMnvM.png',
        name: 'KatzSmith Productions',
        origin_country: 'US',
      },
    ],
    production_countries: [
      { iso_3166_1: 'CA', name: 'Canada' },
      { iso_3166_1: 'US', name: 'United States of America' },
    ],
    release_date: '2019-09-04',
    revenue: 473093228,
    runtime: 169,
    spoken_languages: [
      { english_name: 'English', iso_639_1: 'en', name: 'English' },
    ],
    status: 'Released',
    tagline: "You'll Float Again",
    title: 'It Chapter Two',
    video: false,
    vote_average: 6.9,
    vote_count: 5696,
  },

  simular: [
    {
      adult: false,
      backdrop_path: '/fAf4I3h8kDcvm5wQyxyrBmTeDcv.jpg',
      genre_ids: [27],
      original_language: 'en',
      original_title: 'It',
      id: 346364,
      vote_count: 14876,
      title: 'It',
      vote_average: 7.2,
      video: false,
      overview:
        'In a small town in Maine, seven children known as The Losers Club come face to face with life problems, bullies and a monster that takes the shape of a clown called Pennywise.',
      release_date: '2017-09-06',
      poster_path: '/9E2y5Q7WlCVNEhP5GiVTjhEhx1o.jpg',
      popularity: 55.315,
    },
    {
      adult: false,
      backdrop_path: '/nMfH0LMMFk2ovyURkYvyTI99nSo.jpg',
      genre_ids: [37, 18, 12],
      original_language: 'en',
      original_title: 'The Revenant',
      id: 281957,
      vote_count: 14226,
      title: 'The Revenant',
      vote_average: 7.5,
      video: false,
      overview:
        'In the 1820s, a frontiersman, Hugh Glass, sets out on a path of vengeance against those who left him for dead after a bear mauling.',
      release_date: '2015-12-25',
      poster_path: '/ji3ecJphATlVgWNY0B0RVXZizdf.jpg',
      popularity: 44.898,
    },
    {
      adult: false,
      backdrop_path: '/xhIpqPZoZXj28JDFfV6riXEYiNZ.jpg',
      genre_ids: [9648, 27],
      id: 10349,
      original_language: 'en',
      original_title: 'The Dark Half',
      overview:
        "Thad Beaumont is the author of a highly successful series of violent pulp thrillers written under the pseudonym of ‘George Stark’, but when he decides to ‘kill-off’ his alter-ego in a mock ceremony, it precipitates a string of sadistic murders matching those in his pulp novels, which are soon discovered to be the work of Stark himself. Looking like a maniacal version of his counterpart, Stark is not so willing to quit the writing game – even if it means coming after Thad's wife and their baby.",
      poster_path: '/gALkBGt1bqdJB5LVWYdsCXFpIF6.jpg',
      release_date: '1993-04-23',
      title: 'The Dark Half',
      video: false,
      vote_average: 5.9,
      vote_count: 242,
      popularity: 11.504,
    },
    {
      adult: false,
      backdrop_path: '/2v6hzV33XZn1S4U40E4ZTYwP1eZ.jpg',
      genre_ids: [80, 18, 9648, 53],
      id: 317091,
      original_language: 'en',
      original_title: 'November Criminals',
      overview:
        'When Addison investigates the murder of his friend Kevin with the help of Phoebe, they discover that the truth is darker than they had ever imagined.',
      poster_path: '/m2JxGgarPvtemudLZ1CB6gLJeUb.jpg',
      release_date: '2017-12-08',
      title: 'November Criminals',
      video: false,
      vote_average: 5.2,
      vote_count: 439,
      popularity: 11.029,
    },
    {
      adult: false,
      backdrop_path: '/jArl1j9sL2mYjRW23EaZKWAr2E8.jpg',
      genre_ids: [18, 36, 53],
      id: 399121,
      original_language: 'fr',
      original_title: 'J’accuse',
      overview:
        "In 1894, French Captain Alfred Dreyfus is wrongfully convicted of treason and sentenced to life imprisonment at Devil's Island.",
      poster_path: '/dPMQvBreDBLcztYNTdDZQrLPuO6.jpg',
      release_date: '2019-09-30',
      title: 'An Officer and a Spy',
      video: false,
      vote_average: 7.1,
      vote_count: 907,
      popularity: 21.684,
    },
    {
      backdrop_path: '/sw7mordbZxgITU877yTpZCud90M.jpg',
      genre_ids: [18, 80],
      original_language: 'en',
      original_title: 'GoodFellas',
      poster_path: '/6QMSLvU5ziIL2T6VrkaKzN2YkxK.jpg',
      title: 'GoodFellas',
      vote_average: 8.4,
      vote_count: 8597,
      overview:
        'The true story of Henry Hill, a half-Irish, half-Sicilian Brooklyn kid who is adopted by neighbourhood gangsters at an early age and climbs the ranks of a Mafia family under the guidance of Jimmy Conway.',
      release_date: '1990-09-12',
      id: 769,
      video: false,
      adult: false,
      popularity: 31.157,
    },
    {
      adult: false,
      backdrop_path: '/hrchlLkjT0ejyp7tWIprCZxRHm.jpg',
      genre_ids: [80, 18],
      id: 390584,
      original_language: 'en',
      original_title: 'King Cobra',
      overview:
        'When a lonely suburban man turned gay porn producer discovers a hot, lucrative new star, he finds himself the target of rival pornographers who will stop at nothing to steal his money maker.',
      poster_path: '/sEun5y2q3aIrmpIAAhtS9G2JwH0.jpg',
      release_date: '2016-10-21',
      title: 'King Cobra',
      video: false,
      vote_average: 5.7,
      vote_count: 367,
      popularity: 13.188,
    },
    {
      adult: false,
      backdrop_path: '/bvbyidkMaBls1LTaIWYY6UmYTaL.jpg',
      genre_ids: [878, 28],
      original_language: 'en',
      original_title: 'Maze Runner: The Death Cure',
      id: 336843,
      vote_count: 5515,
      title: 'Maze Runner: The Death Cure',
      vote_average: 7.1,
      video: false,
      overview:
        'Thomas leads his group of escaped Gladers on their final and most dangerous mission yet. To save their friends, they must break into the legendary Last City, a WCKD-controlled labyrinth that may turn out to be the deadliest maze of all. Anyone who makes it out alive will get answers to the questions the Gladers have been asking since they first arrived in the maze.',
      release_date: '2018-01-10',
      poster_path: '/2zYfzA3TBwrMC8tfFbpiTLODde0.jpg',
      popularity: 96.318,
    },
    {
      adult: false,
      backdrop_path: '/omoWcwdARBsGHdMdHUk0AQhS2Lp.jpg',
      genre_ids: [12, 28, 878],
      original_language: 'en',
      original_title: 'The Hunger Games: Catching Fire',
      id: 101299,
      vote_count: 13606,
      title: 'The Hunger Games: Catching Fire',
      vote_average: 7.4,
      video: false,
      overview:
        'Katniss Everdeen has returned home safe after winning the 74th Annual Hunger Games along with fellow tribute Peeta Mellark. Winning means that they must turn around and leave their family and close friends, embarking on a "Victor\'s Tour" of the districts. Along the way Katniss senses that a rebellion is simmering, but the Capitol is still very much in control as President Snow prepares the 75th Annual Hunger Games (The Quarter Quell) - a competition that could change Panem forever.',
      release_date: '2013-11-15',
      poster_path: '/7c1JtraYsjMMnk8Md0IMoyRzqZJ.jpg',
      popularity: 40.149,
    },
    {
      adult: false,
      backdrop_path: '/yukdRXb2bhpwDtCHKvQpQ0q77pd.jpg',
      genre_ids: [18, 27],
      original_language: 'en',
      original_title: 'Freaks',
      poster_path: '/j2dwljljOrLTcnwfKeUBBeNB8t7.jpg',
      video: false,
      id: 136,
      vote_count: 693,
      overview:
        "A circus' beautiful trapeze artist agrees to marry the leader of side-show performers, but his deformed friends discover she is only marrying him for his inheritance.",
      release_date: '1932-02-12',
      vote_average: 7.8,
      title: 'Freaks',
      popularity: 11.532,
    },
    {
      id: 112454,
      original_title: 'Clown',
      poster_path: '/lxn0xeqV2M9P9sEoiLoXlR7121p.jpg',
      title: 'Clown',
      video: false,
      vote_average: 5.5,
      overview:
        "A loving father finds a clown suit for his son's birthday party, only to realize the suit is part of an evil curse that turns its wearer into a killer.",
      release_date: '2014-11-13',
      adult: false,
      backdrop_path: '/sbuvH7mL7qDZozBCRUrPaP1WbqS.jpg',
      vote_count: 944,
      genre_ids: [27],
      original_language: 'en',
      popularity: 40.06,
    },
    {
      adult: false,
      backdrop_path: '/9NoBsVuZA1O51xsUkTTHZgqGBs0.jpg',
      genre_ids: [27, 37, 53],
      id: 541560,
      original_language: 'en',
      original_title: 'The Wind',
      overview:
        'A supernatural thriller set in the Western frontier of the late 1800s, The Wind stars Caitlin Gerard as a plains-woman driven mad by the harshness and isolation of the untamed land.',
      poster_path: '/kcfPHZHSQODLCWdkUVLYATNyEVo.jpg',
      release_date: '2019-06-06',
      title: 'The Wind',
      video: false,
      vote_average: 5.6,
      vote_count: 128,
      popularity: 12.065,
    },
    {
      vote_average: 6.7,
      overview:
        'A spellbinding and romantic supernatural thriller. Ten years after an apocalyptic event left the world haunted by ghosts, Roni receives a threatening message from beyond the grave. Joining forces with a mysterious classmate, Kirk, Roni descends into a shadow world that blurs the bounds of the living and the dead-and begins a desperate race against time to stop a cunning killer.',
      release_date: '2018-09-27',
      adult: false,
      backdrop_path: '/7rqpB7coXaNvTVMWb5vL8qU0pBp.jpg',
      vote_count: 443,
      genre_ids: [53, 14],
      id: 448095,
      original_language: 'en',
      original_title: 'I Still See You',
      poster_path: '/9fqzZs922V8OmwgO11Eqclof2mQ.jpg',
      title: 'I Still See You',
      video: false,
      popularity: 20.278,
    },
    {
      adult: false,
      backdrop_path: '/8VFea9nnOcHEYzBtfTDDKdPe7xj.jpg',
      genre_ids: [18, 10751, 14, 12],
      original_language: 'en',
      original_title: 'Die unendliche Geschichte',
      id: 34584,
      vote_count: 2813,
      title: 'The NeverEnding Story',
      vote_average: 7.2,
      video: false,
      overview:
        "While hiding from bullies in his school's attic, a young boy discovers the extraordinary land of Fantasia, through a magical book called The Neverending Story. The book tells the tale of Atreyu, a young warrior who, with the help of a luck dragon named Falkor, must save Fantasia from the destruction of The Nothing.",
      release_date: '1984-04-05',
      poster_path: '/jq67Zg1TVXNZxTvcXxfIdxK3IWV.jpg',
      popularity: 54.006,
    },
    {
      adult: false,
      backdrop_path: '/3uwyXMZN93PRkShUxvLrufwVAc2.jpg',
      genre_ids: [80, 18, 27, 36],
      id: 452507,
      original_language: 'en',
      original_title: '1922',
      overview:
        'A simple yet proud rancher conspires to murder his wife for financial gain, convincing his teenage son to participate.',
      poster_path: '/q4FQOiSRhTLWulHl5Vpg37FMArH.jpg',
      release_date: '2017-10-20',
      title: '1922',
      video: false,
      vote_average: 5.9,
      vote_count: 1925,
      popularity: 20.433,
    },
    {
      genre_ids: [16, 9648, 27, 878],
      original_language: 'ja',
      original_title: '屍者の帝国',
      poster_path: '/gtfQzn3lRnJ2P3CcE8yxOtXPHTC.jpg',
      video: false,
      vote_average: 6.1,
      id: 342588,
      overview:
        'The story of The Empire of Corpses takes place in 19th century Europe, and revolves around John Watson. He is scouted by the government to become a secret agent- However, Watson lives in a world where "Frankensteins"- human corpses that are re-purposed with a false soul in order to use them as laborers- are used to improve industrial development.',
      release_date: '2015-10-02',
      vote_count: 60,
      title: 'The Empire of Corpses',
      adult: false,
      backdrop_path: '/quWg9dTnqhIwxSwd0HHVXkZ1g8w.jpg',
      popularity: 41.114,
    },
    {
      overview:
        'Fictional drama based on actual events, about two teenage girls who encounter an Internet predator.',
      release_date: '2011-05-01',
      adult: false,
      backdrop_path: '/btOyD8MJyMEPE0vrbHiJCc8PvqY.jpg',
      genre_ids: [18, 27, 53],
      vote_count: 376,
      original_language: 'en',
      original_title: 'Megan Is Missing',
      poster_path: '/mskrdAHmCbwnvSqHGCuVgIZh12L.jpg',
      video: false,
      id: 63197,
      vote_average: 6.2,
      title: 'Megan Is Missing',
      popularity: 31.071,
    },
    {
      adult: false,
      backdrop_path: '/Ya6fu0V9PEH0Q6A4p7qrMmsOS2.jpg',
      genre_ids: [14, 35, 10751],
      original_language: 'en',
      original_title: 'Nanny McPhee',
      poster_path: '/AskzEIoFvIYnYClCW6DyoYDHZ9J.jpg',
      id: 11283,
      video: false,
      title: 'Nanny McPhee',
      vote_count: 2281,
      overview:
        "Widower Cedric Brown hires Nanny McPhee to care for his seven rambunctious children, who have chased away all previous nannies. Taunted by Simon and his siblings, Nanny McPhee uses mystical powers to instill discipline. And when the children's great-aunt and benefactor, Lady Adelaide Stitch, threatens to separate the kids, the family pulls together under the guidance of Nanny McPhee.",
      release_date: '2005-10-21',
      vote_average: 6.6,
      popularity: 25.9,
    },
    {
      backdrop_path: '/qAvou7F5P4VcIR72JzzrnKEQSN3.jpg',
      genre_ids: [12, 14, 10751],
      original_language: 'en',
      original_title: 'The Wizard of Oz',
      poster_path: '/pfAZFD7I2hxW9HCChTuAzsdE6UX.jpg',
      title: 'The Wizard of Oz',
      vote_average: 7.6,
      vote_count: 4002,
      overview:
        'Young Dorothy finds herself in a magical world where she makes friends with a lion, a scarecrow and a tin man as they make their way along the yellow brick road to talk with the Wizard and ask for the things they miss most in their lives. The Wicked Witch of the West is the only thing that could stop them.',
      release_date: '1939-08-15',
      video: false,
      id: 630,
      adult: false,
      popularity: 51.958,
    },
    {
      title: 'Alice in Wonderland',
      original_language: 'en',
      original_title: 'Alice in Wonderland',
      poster_path: '/o0kre9wRCZz3jjSjaru7QU0UtFz.jpg',
      video: false,
      vote_average: 6.6,
      overview:
        "Alice, an unpretentious and individual 19-year-old, is betrothed to a dunce of an English nobleman. At her engagement party, she escapes the crowd to consider whether to go through with the marriage and falls down a hole in the garden after spotting an unusual rabbit. Arriving in a strange and surreal place called 'Underland,' she finds herself in a world that resembles the nightmares she had as a child, filled with talking animals, villainous queens and knights, and frumious bandersnatches. Alice realizes that she is there for a reason – to conquer the horrific Jabberwocky and restore the rightful queen to her throne.",
      id: 12155,
      vote_count: 11029,
      adult: false,
      backdrop_path: '/20pkC7yJdCV4J1IMKfsCT9QU7zV.jpg',
      release_date: '2010-03-03',
      genre_ids: [10751, 14, 12],
      popularity: 34.045,
    },
  ],

  reviews: [
    {
      author: 'SWITCH.',
      author_details: {
        name: 'SWITCH.',
        username: 'maketheSWITCH',
        avatar_path: '/klZ9hebmc8biG1RC4WmzNFnciJN.jpg',
        rating: 8.0,
      },
      content:
        "‘It Chapter 2’ isn’t as stable or as refined a film as its predecessor, and while it feels lacking by comparison, it’s still far better than most studio horror films. It’s epic, ambitious, crazy, witty and unafraid to go for the heart as well as the throat. As a whole, this adaptation of maybe Stephen King’s greatest work feels singular in the landscape of modern horror cinema: two films built on strong interconnected relationships spread over decades, as sentimental as they are vicious, and executed on the scale of a fantasy epic. They also may be amongst the best adaptations of King’s work, understanding what makes his writing (and this novel in particular) so horrifying and so arresting, the human horror amongst the fantastical. Andy Muschietti aimed big with ‘It’, and even in the moments its reach exceeds its grasp, you’re still so glad it reached so high in the first place.\r\n- Daniel Lammin\r\n\r\nRead Daniel's full article...\r\nhttps://www.maketheswitch.com.au/article/review-it-chapter-2-the-ambitious-conclusion-to-the-beloved-horror-epic",
      created_at: '2019-09-04T14:05:06.156Z',
      id: '5d6fc492e22d28000fb54250',
      updated_at: '2019-09-05T16:00:31.457Z',
      url: 'https://www.themoviedb.org/review/5d6fc492e22d28000fb54250',
    },
    {
      author: 'msbreviews',
      author_details: {
        name: '',
        username: 'msbreviews',
        avatar_path:
          '/https://secure.gravatar.com/avatar/992eef352126a53d7e141bf9e8707576.jpg',
        rating: 5.0,
      },
      content:
        'If you enjoy reading my Spoiler-Free reviews, please follow my blog :)\r\n\r\nSo, Chapter Two is a sequel to It (2017), and my expectations were a bit high. I really enjoyed the latter to the point of considering it one of the year’s best, as well as one of the best Stephen King cinematic adaptations. Andy Muschietti returning to the director’s chair and having such a fantastic cast portraying the adult versions of the Losers (not only in terms of quality acting but also regarding how well the adults look like the older versions of the young actors) are two of the main reasons why I was genuinely excited. Also, the runtime (longest horror movie ever?!) definitely left me wondering how a horror flick could have the same duration of some of the most epic films in cinema…\r\n\r\nWell, I got to be honest: I’m disappointed. It’s not a bad movie, at all, but it doesn’t even come close to its predecessor’s heels. I disagree with some headlines I’ve read though. Some say the comedy was misplaced, taking away impact from emotional or dark moments. There’s barely a moment where it was expected seriousness and laughter kicked in instead, but when it does occur, it actually works. I just think it wasn’t as funny as the previous film, overall. Granted, Bill Hader as Richie Tozier is hilarious, and a perfect cast as an adult Finn Wolfhard. His chemistry with James Ransone (Eddie Kaspbrak) resembles the one Wolfhard, and Jack Dylan Grazer had, therefore this/these duo(s) being the comedy highlight.\r\n\r\nSome say the movie is too long. Now, this is a tricky one. Usually, when people feel bored or not as entertained as they wanted to be, they tend to blame it on the film’s runtime, especially if it’s over 100 minutes. I agree that the movie FEELS long, but I disagree that the runtime is too long. There’s more than enough story to explore, and literally, every single character from the Losers Club has an interesting arc. The problem here is that not all of them are explored in a way that’s funny, scary, or just captivating enough. The fact that Jessica Chastain’s (Beverly Marsh) sequence with the old lady is entirely displayed in one of the trailers (and consequently shown at every single screening) doesn’t help the pacing.\r\n\r\nThe first act is pretty decent. As expected, it shows us where everyone is, what they’re doing for a living, and how they get back together. During this act, it’s pretty clear that Muschietti is going to give time to develop each character and follow their respective arcs to the end, hence the lengthy runtime. However, the second act falls flat. Bill Denbrough (James McAvoy / Jaeden Martell) has the most emotionally impactful storyline, one that affects the main plot, making the time that is spent with him worth it. Same goes for Richie’s subplot. On the opposite side, the rest of the group doesn’t have entertaining sequences or new developments whatsoever.\r\n\r\nBeverly continues to be affected by her childhood of abuse from her father. Ben Hanscom (Jay Ryan / Jeremy Ray Taylor) keeps being in love with Bev. Eddie is still a whiny little “kid” who’s scared of everything that might make him ill. Stanley Uris (Andy Bean / Wyatt Oleff) doesn’t do anything, and Mike Hanlon is surprisingly the engine that moves the plot forward, which is a problem of its own since I never really cared for that character (he was definitely the one put aside in the 2017’s movie). Honestly, he just serves as an exposition device considering he spends the whole time just explaining everything the audience needs to know to understand where the film is going.\r\n\r\nFinally, the third act is a mixed bag. While it does provide a climactic ending with a sweet message, it feels very much like its predecessor. I don’t want to spoil anything, but it’s incredibly repetitive comparing to the first movie. Considering all things together, it’s a big letdown since it feels like the exact same film, but with older versions of the characters. Obviously, each of them has a different arc in this one, something the first didn’t have the time to explore, but looking at the main story, it’s pretty much the exact same thing, including how it ends (just with a minor twitch). Nevertheless, the performances are all great… \r\n\r\nJames McAvoy continues his streak of amazing displays, and Bill Hader has to be the MVP for the range he demonstrates. I wish Skarsgård had more time to shine as Pennywise, though. In 2017, I thought he really nailed the character and made it his own. Unfortunately, this time around, Pennywise doesn’t have that much screentime (such a disappointment), and when it appears, it often looks too CGI-ish, taking away from the gripping performance of its actor. The finale has almost no Bill Skarsgård since there’s so much CGI. Despite that, I congratulate the team(s) behind the makeup, hairstyling, costume, and production design. Derry looks terrific, and the time jumps between the young and the old gang worked seamlessly partially due to these visual achievements.\r\n\r\nAndy Muschietti knows how to work a camera, and the movie is very well-shot. However, he should have been able to come up with creative sequences to deliver a different level of entertainment, especially during the tiresome second act. Gary Dauberman’s screenplay is clever, and it brings this enormous story to a fitting conclusion, but he also could have imagined some new ideas for some of the characters. There are a couple of great sequences though, especially one with Bill going through a theme park tent with illusions. \r\n\r\nIn the end, It Chapter Two fails to deliver a conclusion worthy of its epic runtime. Even with a phenomenal cast, it isn’t as funny, as scary or even as captivating as its predecessor. Its runtime is appropriated having in mind that each character has a personal arc, but only a couple of them are genuinely compelling and entertaining. Therefore, the film feels too long, uneven, and it could have used a bit more creativity when it comes to its climactic finale. Its central story feels very similar to the last movie, its scary sequences are nowhere near the quality seen before, and even though the costume and production design are top-notch, there’s excessive use of CGI on Pennywise. It still carries some emotionally convincing moments, as well as a couple of cool sequences. Overall, it’s … okay.\r\n\r\nRating: C',
      created_at: '2019-09-12T17:04:19.099Z',
      id: '5d7a7a93069f0e10db322bcc',
      updated_at: '2019-09-17T16:58:23.992Z',
      url: 'https://www.themoviedb.org/review/5d7a7a93069f0e10db322bcc',
    },
    {
      author: 'Columbusbuck',
      author_details: {
        name: '',
        username: 'Columbusbuck',
        avatar_path:
          '/https://secure.gravatar.com/avatar/0a18c79e03c2ef3b29298900891dbaac.jpg',
        rating: 9.0,
      },
      content:
        "It's the love story between Richie and Eddie that makes this movie worth viewing twice. Looking forward to the conclusion!",
      created_at: '2019-09-27T17:44:37.030Z',
      id: '5d8e4a85221ba60029b5a0fe',
      updated_at: '2019-10-03T17:18:29.714Z',
      url: 'https://www.themoviedb.org/review/5d8e4a85221ba60029b5a0fe',
    },
    {
      author: 'Gimly',
      author_details: {
        name: 'Gimly',
        username: 'Ruuz',
        avatar_path: '/xUObnJSvHrFPsIpoDmb1jiQZLq7.jpg',
        rating: 7.0,
      },
      content:
        "A pretty odd choice too undercut every scare in the movie, but I was less disappointed with _Chapter Two_ than everyone else seems to be. I gave it the same star rating as the first Muscietti _It_ movie, but if I'm being honest, that one was definitely better. Doesn't make this bad though. \r\n\r\n_Final rating:★★★½ - I really liked it. Would strongly recommend you give it your time._",
      created_at: '2019-10-02T11:57:32.720Z',
      id: '5d9490aca06efe001e5b0700',
      updated_at: '2019-10-03T17:17:28.587Z',
      url: 'https://www.themoviedb.org/review/5d9490aca06efe001e5b0700',
    },
    {
      author: 'JPV852',
      author_details: {
        name: '',
        username: 'JPV852',
        avatar_path: '/xNLOqXXVJf9m7WngUMLIMFsjKgh.jpg',
        rating: 7.0,
      },
      content:
        "Wasn't a huge fan of the first but did like the young cast but the scares were non-existent. This sequel had a couple okay moments and I did like the characters as adults, but Bill Hader easily was the standout. Still wasn't very scary yet even with the lengthy running time never felt like it dragged. One day I may try watching the two back to back, but between the two, not overly impressive. **3.5/5**",
      created_at: '2019-12-07T04:02:25.853Z',
      id: '5deb24515c5cc80014cba2e4',
      updated_at: '2019-12-10T19:23:47.622Z',
      url: 'https://www.themoviedb.org/review/5deb24515c5cc80014cba2e4',
    },
    {
      author: 'Matthew Brady',
      author_details: {
        name: 'Matthew Brady',
        username: 'MatthewL.Brady',
        avatar_path: '/k5J0l25FXOCw4TcX6iWaJmYpCZ4.jpg',
        rating: 7.0,
      },
      content:
        "“You lied and I died!”\r\n\r\nMaking us proud Georgie.\r\n\r\nI re-watched the 1990 mini-series and 2017 remake last month in preparation for this movie in terms of judging in quality. The 90's version had it moments, but I find some scenes unintentionally funny where it reeked of early Stephen King adaptations. 2017 was surprisingly good and a massive improvement, but laid back on cheap thrills.\r\n\r\n‘IT: Chapter Two’ was a tough act to follow up on after the monster success of the first and with the second chapter being the hardest to adapt. I thought the movie both succeeds and stumbles in parts. Although reflecting back makes it feel more like a parody than a serious horror movie. An epic finale that ended in a over the top fashion - with themes of childhood trauma and the idea of holding on to the past despite growing up with age are sprinkled through out. The loser club are all grown up now and returning home to kill IT.\r\n\r\nWhoever cast the grow up version of the loser club deserves massive praise here, because it’s pitch perfect casting and I could definitely see the child stars growing up to be the adult stars. James McAvoy, Jessica Chastain, Jay Ryan, and Isaiah Mustafa were all great in bringing the more dramatic aspects to the film. While Bill Hader and James Ranson bring the comedic aspects, but not to say they weren't dramatic as well, even making me tear up at one point.\r\n\r\nBill Skarsgard was truly amazing as Pennywise. The physicality in his movement has a certain silliness that you would expect to see from a clown, yet predatory with his animal-like attacks with drool running down his mouth and eyes staring in opposite directions despite looking straight at you. I find the dancing clown incredibly terrifying whenever he becomes playful and kind to deceive children.\r\n\r\nAndy Muschietti truly shines as a director when it comes to bizarre imagery and unsettling camera angles, while also capturing some real emotions through the lens. The opening scene at the bridge where a homophobic attack takes place was really brutal and starts the movie off strong - on par with the Georgie meets Pennywise scene in the first movie.\r\n\r\nDespite the run time being nearly three hours long, but I can’t recall ever being bored. It moved at a even pace in my opinion. I guess a few scenes could’ve been cut as most of it is unused footage from the first movie. Although it would be difficult to cut scenes as everything follows up to the next scene and that emotional punch towards the end wouldn’t be earned.\r\n\r\nNow for the issues:\r\n\r\nHenry Bowers was completely pointless in this movie and was only used for jump scars. Same thing with Mike, who through out these movies has nothing to do and the important things he did in the book was given to different characters.\r\n\r\nI didn’t like how Stan’s suicide was handle, because you find out he actually “sacrificed” himself to save the others.\r\n\r\nSome of the humor didn’t always land, especially if it’s right after a tense scene where it kinda deflates the horror. At times I struggled to gasp what the film marker was going for in certain scenes. Is this scene suppose to be scary or funny? Both maybe?\r\n\r\nI wish there was more practical work for the monster scenes instead of CGI, because at times it looked really terrible. The finale battle at the end could’ve been in a video game boss fight.\r\n\r\n* Overall rating: Not as strong as the first, but still enjoyed it. Still, let’s kill this f**king clown.**strong text**",
      created_at: '2020-01-27T18:04:36.238Z',
      id: '5e2f26341685da0019e932b9',
      updated_at: '2020-01-28T15:03:29.790Z',
      url: 'https://www.themoviedb.org/review/5e2f26341685da0019e932b9',
    },
    {
      author: 'r96sk',
      author_details: {
        name: '',
        username: 'r96sk',
        avatar_path:
          '/https://secure.gravatar.com/avatar/96c2e0e4ac98450f9e8e3c0a0a40aad8.jpg',
        rating: 8.0,
      },
      content:
        "A step down, but <em>'It Chapter Two'</em> is still a very good film.\r\n\r\nIt is, I will say, overly long, it did bore me a little at the midway point; not in a necessarily negative way, I just wanted more. However, it regains its footing with an entertaining ending. I'm usually not a fan of cast changes in film series, but this does it to good effect. I love the characters, whether it be in this film or the preceding entry.\r\n\r\nJessica Chastain and Bill Hader are great choices to play the older versions of Sophia Lillis and Finn Wolfhard, they are very convincing casts. James McAvoy is also a positive addition, while Bill Skarsgård remains enjoyable as It.\r\n\r\nThe score is, again, strong. I like the plot, even if I do feel like it's stretched out and could've had more freshness added to it. It isn't as creepy as the first film either, but still has a solid amount of uneasiness.",
      created_at: '2020-12-29T16:53:39.443Z',
      id: '5feb5f1364f716003e0f6ff8',
      updated_at: '2020-12-31T16:15:25.581Z',
      url: 'https://www.themoviedb.org/review/5feb5f1364f716003e0f6ff8',
    },
  ],
}
